# Generated by Django 2.0.6 on 2018-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayures', '0001_squashed_0003_auto_20180621_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayureeventprocessingerror',
            name='func',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rayureeventprocessingerror',
            name='message',
            field=models.TextField(),
        ),
    ]
